### PR TITLE
Compare store prices

### PR DESCRIPTION
**Pull request by davisethan**

### CODE REVIEW

**Comment by yamaser** [comment]
I think the UI looks great; it's exactly what I had in mind.

I noticed some unexpected behavior when testing:
1. When clicking on the details button for Fred Meyer and New Seasons Market, I noticed that some items were marked as NA (all fields for particular items show NA). I double-checked the remote database and they're in there.
2. I think there's a problem with one of the SQL queries. The query is not always picking the latest price. One example is [scan_id = 27, item_id = 4, store_id =1, price_time = 2022-01-18 19:46:38] which is the most recent price_time for that item at that store -- the price in the database shows 4.19, but the query returns 4.49. I've run into this issue before; this should help explain: https://stackoverflow.com/questions/9469852/mysql-query-max-not-working

**Comment by davisethan** [comment]
1. The NA values are for cart items tags which aren't a subset of (all) scanned item tags
2. I fixed the query

**Comment by yamaser** [comment]
1. I didn't know that's why 'NA' was showing up. I feel bad saying this because of all the great code I see in router.js, but I think we should reconsider if/how we should filter based on cart item tags and scan tags. This is more of a UI/UX/app-value issue rather than a technical issue.
2. Query works as far as I can tell. Thanks!

**Review by codyhho — APPROVED** [review]
Compare page seems to work great!

**Pull request merged**
